#
# Module manifest for module 'Dramatic.PSeDOCS'
#
# Generated by: Victor Vogelpoel
#
# Generated on: 25-7-2017
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'Dramatic.PSeDOCS'

# Version number of this module.
ModuleVersion = '0.1'

# ID used to uniquely identify this module
GUID = '5b78fc6d-8fe1-4f2c-bc87-61837e32a6ca'

# Author of this module
Author = 'Victor Vogelpoel'

# Company or vendor of this module
CompanyName = 'Dramatic Development'

# Copyright statement for this module
Copyright = 'Copyright 2017 Dramatic Development'

# Description of the functionality provided by this module
Description = 'PowerShell Module for working with OpenText eDOCS DM'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '4.0'

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of the .NET Framework required by this module
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @("Base64.Types.ps1xml")

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module
# FunctionsToExport = '*'

# Cmdlets to export from this module
# CmdletsToExport = '*'

# Variables to export from this module
#VariablesToExport = '*'

# Aliases to export from this module
#AliasesToExport = '*'

# List of all modules packaged with this module.
# ModuleList = @()

# List of all files packaged with this module
FileList = @(	'.\Dramatic.PSeDOCS.psm1')

# Private data to pass to the module specified in RootModule/ModuleToProcess
PrivateData = @{
    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @('eDOCS')

        # A URL to the license for this module.
        LicenseUri = ''

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/victorvogelpoel/Dramatic.PSeDOCS'

        # A URL to an icon representing this module.
        #IconUri = 'https://github.com/victorvogelpoel/Dramatic.PSeDOCS/blob/master/...'

        # ReleaseNotes of this module
        ReleaseNotes = 'https://github.com/DramaticSolutions/Dramatic.PSeDOCS/blob/master/RELEASENOTES.TXT'

        # External Module Dependencies
        # ExternalModuleDependencies = @('VMware.VimAutomation.Core')

    } # End of PSData hashtable
}

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = 'DM'

}